# -*- coding: utf-8 -*-
"""streamlitt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WA1aBSXDZGV3lKWAhhyF4GoE20L7QE4b
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Fitness_App.py
# import numpy as np
# import streamlit as st
# import pandas as pd
# from sklearn.tree import DecisionTreeClassifier
# 
# st.write(''' # Predicción de condición física ''')
# 
# st.header('Datos de evaluación')
# 
# def user_input_features():
#   age = st.number_input('Edad:', min_value=0, max_value=120, value=25, step=1)
#   height_cm = st.number_input('Altura (cm):', min_value=100, max_value=250, value=170, step=1)
#   weight_kg = st.number_input('Peso (kg):', min_value=20, max_value=250, value=70, step=1)
#   heart_rate = st.number_input('Frecuencia cardiaca (lat/min):', min_value=30, max_value=200, value=70)
#   blood_pressure = st.number_input('Presión arterial sistólica (mmHg):', min_value=60, max_value=200, value=120)
#   sleep_hours = st.number_input('Horas de sueño (promedio):', min_value=0.0, max_value=24.0, value=8.0)
#   nutrition_quality = st.number_input('Calidad nutricional (0–10):', min_value=0.0, max_value=10.0, value=5.0)
#   activity_index = st.number_input('Índice de actividad (1–5):', min_value=1.0, max_value=5.0, value=3.0)
#   smokes = st.number_input('Fuma (0=No, 1=Sí):', min_value=0, max_value=1, value=0, step=1)
#   gender = st.number_input('Género (0=F, 1=M):', min_value=0, max_value=1, value=1, step=1)
# 
#   user_input_data = {
#       'age': age,
#       'height_cm': height_cm,
#       'weight_kg': weight_kg,
#       'heart_rate': heart_rate,
#       'blood_pressure': blood_pressure,
#       'sleep_hours': sleep_hours,
#       'nutrition_quality': nutrition_quality,
#       'activity_index': activity_index,
#       'smokes': smokes,
#       'gender': gender
#   }
# 
#   features = pd.DataFrame(user_input_data, index=[0])
#   return features
# 
# df = user_input_features()
# 
# fitness = pd.read_csv('Fitness2.csv')
# 
# X = fitness.drop(columns='is_fit')
# Y = fitness['is_fit']
# 
# classifier = DecisionTreeClassifier(
#     max_depth=3,
#     criterion='entropy',
#     min_samples_leaf=25,
#     max_features=5,
#     random_state=1613808
# )
# 
# classifier.fit(X, Y)
# 
# prediction = classifier.predict(df)
# 
# st.subheader('Predicción')
# if prediction == 0:
#   st.write('No está en forma')
# elif prediction == 1:
#   st.write('Sí está en forma')
# else:
#   st.write('Sin predicción')
#